import { Link } from 'react-router-dom'
import { usePageMeta } from '../usePageMeta'

const phases = [
  { name:'Prepare', color:'#0755ae', intro:'Get your paperwork, age, and education lined up before you visit the DMV.', items:['Be between the ages of 15½ and 18.','Complete an approved California driver education course or enroll in a training program.','Complete the DL 44 application with a parent or guardian signature.','Make an appointment at the DMV office for faster service.','Bring all required forms.'] },
  { name:'Provide', color:'#e12d3c', intro:'At the office you will verify identity, pay the fee, and complete biometrics.', items:['Submit your driver education certificate to the DMV.','Provide your Social Security number.','Verify your birth date and legal presence.','Provide your true full legal name.','Give a thumb print.','Have your picture taken.','Pay the DMV application fee.'] },
  { name:'Pass', color:'#063b82', intro:'Finish with a quick vision screening and the written knowledge test.', items:['Pass a vision exam.','Pass the traffic laws and signs test. The test has 46 questions and three attempts.','Use permit-prep practice tests if you need a refresher before your exam.'] },
]

export default function OnlineCoursePermitPage(){
  usePageMeta("How to Get a California Driver's Permit",'Learn the steps and requirements for obtaining a California learner permit.')
  return <div className="pp-page"><style>{`
    .pp-page{padding-top:10rem;background:#f3f7fd;color:#071b34;font-family:var(--font-body);min-height:100vh}.pp-wrap{width:min(1060px,calc(100% - 2rem));margin:auto}.pp-nav{position:sticky;top:4.5rem;z-index:30;margin-top:1rem;background:#06285f}.pp-nav-in{min-height:58px;display:flex;align-items:center;justify-content:center;gap:.4rem 1rem;overflow-x:auto;scrollbar-width:none}.pp-nav a{flex:0 0 auto;padding:.72rem 1rem;border-radius:7px;color:#fff;font-size:.76rem;font-weight:800;text-decoration:none;text-transform:uppercase;white-space:nowrap}.pp-nav a:hover{background:#FDBC01;color:#0145A8}.pp-nav a.active{color:#FDBC01;text-shadow:0 0 12px rgba(253,188,1,.6)}
    .pp-head{padding:3.5rem 1rem;text-align:center;background:#eaf1fc;border-bottom:1px solid #d7e1ef}.pp-head h1{margin:0 0 1.2rem;font-family:var(--font-display);font-size:clamp(2rem,5vw,3rem)}.pp-facts{display:flex;justify-content:center;gap:.7rem;flex-wrap:wrap}.pp-fact{padding:.6rem 1rem;border-radius:8px;background:#fff;box-shadow:0 5px 15px rgba(15,40,75,.08);font-size:.75rem;text-transform:uppercase;color:#334155}.pp-fact strong{color:#063b82;margin-left:.35rem}
    .pp-content{padding:3.5rem 0}.pp-phases{display:flex;flex-direction:column;gap:1.7rem}.pp-card{position:relative;background:#fff;border-radius:14px;box-shadow:0 10px 28px rgba(15,40,75,.08);overflow:hidden}.pp-card-head{padding:1.5rem;display:flex;align-items:center;gap:1rem;border-bottom:1px solid #e7edf4}.pp-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:12px;background:#edf2f7;font-size:1.5rem}.pp-card h2{margin:.15rem 0 0;font-size:1.5rem}.pp-num{position:absolute;right:1.5rem;top:1rem;color:#e2e8f0;font-size:3rem;font-weight:900}.pp-body{padding:1.4rem}.pp-body p{color:#334155}.pp-list{padding:0;list-style:none}.pp-list li{padding:.8rem 0;border-bottom:1px dotted #cbd5e1;color:#334155}.pp-list li:last-child{border:0}.pp-list li:before{content:'✓';display:inline-grid;place-items:center;width:18px;height:18px;margin-right:.7rem;border:1.5px solid #e12d3c;border-radius:50%;color:#e12d3c;font-size:.7rem;font-weight:900}
    .pp-cta{margin-top:4rem;display:grid;grid-template-columns:.8fr 1.2fr;border-radius:14px;overflow:hidden;background:#fff;box-shadow:0 15px 40px rgba(15,40,75,.12)}.pp-price{display:grid;place-items:center;padding:2rem;background:linear-gradient(135deg,#061c45,#063b82);color:#fff;text-align:center}.pp-price strong{font-family:var(--font-display);font-size:3rem}.pp-buy{padding:2rem;display:flex;flex-direction:column;justify-content:center}.pp-btn{width:max-content;padding:.8rem 1.3rem;border-radius:6px;background:#d92332;color:#fff;font-weight:800;text-decoration:none}
    @media(max-width:760px){.pp-page{padding-top:9.5rem}.pp-nav{margin-top:.5rem}.pp-nav-in{justify-content:flex-start;padding-inline:.6rem}.pp-cta{grid-template-columns:1fr}.pp-card-head{padding-right:4rem}}
  `}</style>
  <nav className="pp-nav" aria-label="Online course sections"><div className="pp-wrap pp-nav-in"><Link to="/online-drivers-ed">Home</Link><Link to="/online-drivers-ed/details">Course Details</Link><Link to="/online-drivers-ed/pricing">Pricing</Link><Link className="active" aria-current="page" to="/online-drivers-ed/permit">Permit</Link><Link to="/online-drivers-ed/driver-license">Driver License</Link><Link to="/">Behind the Wheel</Link></div></nav>
  <section className="pp-head"><h1>How to Get a Driver's Permit</h1><div className="pp-facts"><span className="pp-fact">Ages <strong>15½–18</strong></span><span className="pp-fact">Fee <strong>DMV rate</strong></span><span className="pp-fact">Written Test <strong>46 questions</strong></span><span className="pp-fact">Attempts <strong>3 tries</strong></span></div></section>
  <main className="pp-content"><div className="pp-wrap"><div className="pp-phases">{phases.map((phase,i)=><section className="pp-card" key={phase.name} style={{borderTop:`4px solid ${phase.color}`}}><div className="pp-card-head"><div className="pp-icon" style={{color:phase.color}}>{['▤','▣','✓'][i]}</div><div><small style={{color:'#334155',fontWeight:800}}>PHASE {i+1}</small><h2>{phase.name}</h2></div><div className="pp-num">{i+1}</div></div><div className="pp-body"><p>{phase.intro}</p><ul className="pp-list">{phase.items.map(item=><li key={item}>{item}</li>)}</ul></div></section>)}</div><section className="pp-cta"><div className="pp-price"><div><small>ONLINE COURSE</small><br/><strong>$39.99</strong></div></div><div className="pp-buy"><h2>California DMV-Approved Teen Driver Education</h2><p style={{color:'#334155'}}>100% online, self-paced lessons with your official completion certificate included.</p><Link className="pp-btn" to="/register">Sign Up Now</Link></div></section></div></main>
  </div>
}
