import { useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { signOut } from 'firebase/auth'
import { auth } from '../firebase'
import { usePageMeta } from '../usePageMeta'

const CHAPTERS = [
  { title: 'Driving Is Your Responsibility', lesson: "Driver's License: A Privilege", intro: 'Driving a motor vehicle requires knowledge, care and a strong sense of responsibility.', points: ['Make safety your first priority whenever you are behind the wheel.', 'Obey traffic rules and signals and be courteous to other road users.', 'Avoid distractions and unnecessary risks.', 'Understand how your vehicle works and keep it safe to operate.'], topics: ["Driver's License: A Privilege", 'Obeying the Laws', "Importance of Driver's Education", 'The New Laws in Driving', 'Smoke-Free Cars', 'History of the Automobile', 'Chapter 1 Test'] },
  { title: 'The Human Factors Affecting the Driver', lesson: 'Eyes and Vision', intro: 'Safe decisions depend on vision, hearing, physical condition, attitude and attention.', points: ['Scan far ahead and check mirrors regularly.', 'Recognize fatigue, stress and limited visibility.', 'Stay focused and avoid aggressive behavior.'], topics: ['Eyes and Vision', 'The Ears and Hearing', 'Other Limiting Physical Conditions', 'Essential Attitudes', 'Undesirable Driving Behaviors', 'Chapter 2 Test'] },
  { title: 'Natural Forces Affecting the Automobile', lesson: 'Gravity and Vehicle Control', intro: 'Gravity, inertia, friction and momentum affect every movement of a vehicle.', points: ['Adjust speed before curves and hills.', 'Leave enough room to stop safely.', 'Understand how road surface conditions affect traction.'], topics: ['Gravity', 'Inertia and Momentum', 'Friction and Traction', 'Energy of Motion', 'Chapter 3 Test'] },
  { title: 'Signs, Signals and Highway Markings', lesson: 'Traffic Signs: Shapes and Colors', intro: 'Traffic control devices communicate rules, warnings and guidance to every driver.', points: ['Learn sign shapes and colors.', 'Follow traffic lights and lane-control signals.', 'Read pavement markings before changing position.'], topics: ['Traffic Signs: Shapes and Colors', 'Regulatory Signs', 'Warning Signs', 'Traffic Signals', 'Highway Markings', 'Chapter 4 Test'] },
  { title: 'The Vehicle Systems', lesson: 'Construction of the Automobile', intro: 'A responsible driver understands the controls and safety systems of the vehicle.', points: ['Check tires, lights and fluid levels.', 'Know the purpose of dashboard warnings.', 'Use seat belts and safety equipment correctly.'], topics: ['Construction of the Automobile', 'Control Systems', 'Braking and Steering', 'Tires and Traction', 'Vehicle Maintenance', 'Chapter 5 Test'] },
  { title: 'Rules of the Road and Safe Driving Practices', lesson: 'Defensive Driving', intro: 'Defensive driving helps you anticipate hazards and make safe, lawful decisions.', points: ['Maintain a safe following distance.', 'Yield the right of way when required.', 'Choose a speed suitable for current conditions.'], topics: ['Defensive Driving', 'Right-of-Way Rules', 'Speed and Space Management', 'Lane Changes and Passing', 'Parking', 'Chapter 6 Test'] },
  { title: 'Sharing the Road and Accident Prevention', lesson: 'Tips for Sharing the Road', intro: 'Drivers must safely share the road with pedestrians, cyclists, motorcycles and large vehicles.', points: ['Check blind spots carefully.', 'Give vulnerable road users enough space.', 'Plan an escape path and expect the unexpected.'], topics: ['Sharing the Road', 'Pedestrians and Cyclists', 'Motorcycles', 'Large Vehicles', 'Collision Prevention', 'Chapter 7 Test'] },
  { title: 'Alcohol and Drugs and Driving', lesson: 'Alcohol as a Drug', intro: 'Alcohol, cannabis, medicines and other drugs can impair judgment and vehicle control.', points: ['Never drive while impaired.', 'Plan a sober ride before consuming alcohol.', 'Understand that legal medicines may also affect driving.'], topics: ['Alcohol as a Drug', 'Effects on Driving Ability', 'Other Drugs and Medicines', 'Impaired-Driving Laws', 'Chapter 8 Test'] },
  { title: 'Licensing, Registrations and California Vehicle Codes', lesson: 'California Licensing', intro: 'California law sets requirements for licensing, vehicle registration and financial responsibility.', points: ['Carry a valid license and required documents.', 'Keep registration and insurance current.', 'Understand the responsibilities of a licensed driver.'], topics: ['Licensing', 'Vehicle Registration', 'Financial Responsibility', 'California Vehicle Code', 'Chapter 9 Test'] },
  { title: "Acquiring a California Driver's License", lesson: 'The Licensing Process', intro: 'Follow each permit, practice and testing requirement before applying for a driver license.', points: ['Complete the required driver education.', 'Practice with a qualified supervising driver.', 'Prepare your vehicle and documents for the road test.'], topics: ['Applying for a Permit', 'Knowledge Test', 'Supervised Practice', 'Behind-the-Wheel Test', 'Provisional License', 'Chapter 10 Test'] },
  { title: 'Final Test', lesson: 'Course Final Test', intro: 'Review the complete curriculum before beginning the final knowledge assessment.', points: ['Revisit any chapter that needs more study.', 'Read every question carefully.', 'Apply safe-driving principles to each situation.'], topics: ['Course Review', 'Final Test'] },
]

export default function OnlineEducationCoursePage() {
  usePageMeta('30 Hour Drivers Ed Curriculum — A Precision Driving School', 'Protected online driver education curriculum.', { noIndex: true })
  const navigate = useNavigate()
  const [activeChapter, setActiveChapter] = useState(0)
  const [started, setStarted] = useState(false)
  const chapter = useMemo(() => CHAPTERS[activeChapter], [activeChapter])

  const selectChapter = index => {
    setActiveChapter(index)
    setStarted(false)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  const handleLogout = async () => {
    await signOut(auth)
    navigate('/online-drivers-ed/login', { replace: true })
  }

  return (
    <div className="oe-course-page">
      <style>{`
        .oe-course-page{min-height:100vh;background:#f5f7fb;color:#111827;font-family:var(--font-body)}.oe-course-header{background:#407fca}.oe-course-head-inner{width:min(1460px,calc(100% - 2rem));min-height:130px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:2rem}.oe-course-logo{width:235px;height:auto}.oe-logout{padding:.72rem 1.25rem;border:1px solid #fff;border-radius:6px;background:#b91c1c;color:#fff;font-weight:800;cursor:pointer}
        .oe-course-nav{background:#0733a0}.oe-course-nav-inner{width:min(1460px,calc(100% - 2rem));min-height:52px;margin:auto;display:flex;align-items:center;gap:.25rem}.oe-course-nav a,.oe-course-nav button{padding:.8rem 1rem;border:0;background:none;color:#fff;font:700 .95rem var(--font-body);text-decoration:none;cursor:pointer}.oe-course-nav a:hover,.oe-course-nav button:hover{background:rgba(255,255,255,.12)}
        .oe-course-layout{width:min(1460px,calc(100% - 2rem));margin:1.4rem auto 3rem;display:grid;grid-template-columns:360px minmax(0,1fr);gap:1.1rem;align-items:start}.oe-curriculum,.oe-lesson-card{border:1px solid #cbd5e1;background:#fff}.oe-panel-title{margin:0;padding:1rem;background:#0733a0;color:#fff;font-family:var(--font-display);font-size:1.2rem}.oe-chapter-list{margin:0;padding:0;list-style:none}.oe-chapter-btn{display:grid;grid-template-columns:28px 1fr;width:100%;padding:.9rem .85rem;border:0;border-bottom:1px solid #dbe2ea;background:#f8fafc;color:#43301c;text-align:left;cursor:pointer;line-height:1.35}.oe-chapter-btn:hover{background:#fff8dd}.oe-chapter-btn.active{background:#fff1b8;color:#0733a0;font-weight:800}.oe-check{color:#ef3340;font-weight:900}
        .oe-lesson-title{margin:0;padding:1rem 1.4rem;background:#0733a0;color:#fff;font-family:var(--font-display);font-size:1.2rem}.oe-lesson-body{padding:clamp(1.2rem,3vw,2rem);background:#f7f7f7;min-height:610px}.oe-chapter-kicker{margin:0 0 .8rem;color:#0145a8;font-family:var(--font-display);font-size:clamp(1.35rem,3vw,2rem);font-style:italic}.oe-intro{font-weight:800;font-size:1.05rem}.oe-responsibility{width:150px;height:150px;margin:1.5rem auto;border-radius:50%;display:grid;place-items:center;background:radial-gradient(circle at 35% 30%,#68b9ff,#0569bd 58%,#043b77);color:#fff;text-align:center;font:900 .78rem var(--font-mono);letter-spacing:.08em;box-shadow:0 15px 30px rgba(1,69,168,.2)}.oe-points{max-width:850px;margin:1rem auto;line-height:1.55}.oe-topics{display:grid;gap:.35rem;margin:1.2rem 0;font-weight:700}.oe-topic-number{color:#0145a8;font-family:var(--font-mono);margin-right:.45rem}.oe-start-wrap{text-align:center;margin-top:1.6rem}.oe-start{padding:.85rem 1.2rem;border:0;border-radius:6px;background:#273242;color:#fff;font-weight:800;cursor:pointer}.oe-start.started{background:#15803d}.oe-lesson-note{max-width:760px;margin:1rem auto 0;padding:.85rem 1rem;border:1px solid #bbf7d0;border-radius:7px;background:#f0fdf4;color:#166534;text-align:center}.oe-course-footer{padding:1.2rem;background:#0733a0;color:#dbeafe;text-align:center;font-size:.82rem}
        @media(max-width:900px){.oe-course-head-inner{min-height:100px}.oe-course-logo{width:180px}.oe-course-layout{grid-template-columns:1fr}.oe-curriculum{position:relative}.oe-lesson-body{min-height:auto}.oe-course-nav-inner{overflow-x:auto}.oe-course-nav a,.oe-course-nav button{white-space:nowrap}}
        @media(max-width:520px){.oe-course-head-inner{align-items:center}.oe-course-logo{width:145px}.oe-logout{padding:.6rem .8rem}.oe-course-layout{width:min(100% - 1rem,1460px)}.oe-lesson-body{padding:1rem}}
      `}</style>
      <header className="oe-course-header"><div className="oe-course-head-inner"><img className="oe-course-logo" src="/driving-logo.png" alt="A Precision Driving School" /><button className="oe-logout" type="button" onClick={handleLogout}>Log Out</button></div></header>
      <nav className="oe-course-nav" aria-label="Course navigation"><div className="oe-course-nav-inner"><Link to="/">Home</Link><button type="button" onClick={() => selectChapter(0)}>Course Map</button><Link to="/contact">Contact us</Link></div></nav>
      <main className="oe-course-layout">
        <aside className="oe-curriculum"><h1 className="oe-panel-title">Drivers Ed Curriculum</h1><ol className="oe-chapter-list">{CHAPTERS.map((item,index) => <li key={item.title}><button type="button" className={`oe-chapter-btn${activeChapter === index ? ' active' : ''}`} onClick={() => selectChapter(index)} aria-current={activeChapter === index ? 'true' : undefined}><span className="oe-check">☑</span><span>{index + 1}. {item.title}</span></button></li>)}</ol></aside>
        <section className="oe-lesson-card" aria-live="polite"><h2 className="oe-lesson-title">{chapter.lesson}</h2><div className="oe-lesson-body"><h3 className="oe-chapter-kicker">Chapter {activeChapter + 1}: {chapter.title}</h3><p className="oe-intro">{chapter.intro}</p><div className="oe-responsibility">DRIVE<br />RESPONSIBLY</div><ul className="oe-points">{chapter.points.map(point => <li key={point}>{point}</li>)}</ul><div className="oe-topics">{chapter.topics.map((topic,index) => <div key={topic}><span className="oe-topic-number">{activeChapter + 1}.{index + 1}</span>{topic}</div>)}</div><div className="oe-start-wrap"><button type="button" className={`oe-start${started ? ' started' : ''}`} onClick={() => setStarted(true)}>{started ? 'Lesson Started' : 'Begin Lesson'}</button>{started && <p className="oe-lesson-note">Lesson opened. Use the curriculum menu to continue through each chapter.</p>}</div></div></section>
      </main>
      <footer className="oe-course-footer">Copyright © {new Date().getFullYear()} A Precision Driving School. All rights reserved.</footer>
    </div>
  )
}
