import { Link } from 'react-router-dom'
import { usePageMeta } from '../usePageMeta'

const plans = [
  { name:'Permit Prep', price:'Free', action:'Get Started', features:['500+ DMV practice questions','Real DMV test simulations','Unlimited practice attempts','Road signs and traffic laws','Progress tracking'] },
  { name:'Course Only', price:'$39.99', action:'Buy Plan', features:['State-approved course','Official DMV certificate','Self-paced online training','Mobile and tablet friendly','Learn at your own pace'] },
  { name:'Course + Permit Prep', price:'$59', action:'Buy Plan', features:['State-approved online course','Official completion certificate','Unlimited practice tests','500+ permit prep questions','Mobile-friendly access'] },
]
const benefits=['State-approved and trusted','Options for every stage','Learn 100% online','Built to help you pass','Real support when needed','Fast official certificate','Affordable transparent pricing']
const faqs=[['Is this online course approved by the California DMV?','Yes. The course meets California driver education requirements.'],['Who can take this course?','It is designed for teens preparing to earn their permit.'],['How long does the course take?','Complete it at your own pace; progress is saved automatically.'],['Are there any hidden fees?','No. Pricing is clear and transparent.'],['Can I use a phone or tablet?','Yes. The course works on desktops, laptops, tablets and smartphones.']]

export default function OnlineCoursePricingPage(){
  usePageMeta('Online Driver Education Pricing','Compare online driver education and permit-prep options.')
  return <div className="cp-page"><style>{`
    .cp-page{padding-top:10rem;background:#f3f7fd;color:#071b34;font-family:var(--font-body);min-height:100vh}.cp-wrap{width:min(1060px,calc(100% - 2rem));margin:auto}.cp-nav{position:sticky;top:4.5rem;z-index:30;margin-top:1rem;background:#06285f}.cp-nav-in{min-height:58px;display:flex;align-items:center;justify-content:center;gap:.4rem 1rem;overflow-x:auto;scrollbar-width:none}.cp-nav a{flex:0 0 auto;padding:.72rem 1rem;border-radius:7px;color:#fff;font-size:.76rem;font-weight:800;text-decoration:none;text-transform:uppercase;white-space:nowrap}.cp-nav a:hover{background:#FDBC01;color:#0145A8}.cp-nav a.active{color:#FDBC01;text-shadow:0 0 12px rgba(253,188,1,.6)}
    .cp-hero{padding:3.5rem 0 4rem;background:linear-gradient(rgba(6,40,95,.68),rgba(6,40,95,.68)),url('/hero2.jpg') center/cover}.cp-title{text-align:center;color:#fff;font-family:var(--font-display);font-size:2.4rem;margin:0 0 1.6rem}.cp-plans{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.cp-plan{padding:1.6rem;background:#fff;border-radius:10px;box-shadow:0 15px 35px rgba(5,25,55,.2);text-align:center}.cp-plan h2{font-size:1.1rem}.cp-price{font-family:var(--font-display);font-size:2rem;font-weight:800;color:#405068}.cp-plan ul{padding:0;list-style:none;text-align:left;color:#53657a;font-size:.8rem;line-height:2}.cp-plan li:before{content:'✓';color:#e02d34;font-weight:900;margin-right:.55rem}.cp-btn{display:inline-flex;padding:.7rem 1.2rem;border-radius:6px;background:#d92332;color:#fff;font-weight:800;text-decoration:none}
    .cp-section{padding:4rem 0}.cp-heading{text-align:center;font-family:var(--font-display);font-size:2rem;margin:0 0 2rem}.cp-summary{display:grid;grid-template-columns:280px 1fr;gap:2rem;align-items:center}.cp-summary img{width:100%;height:190px;object-fit:cover;border-radius:12px;box-shadow:0 10px 30px rgba(15,40,75,.15)}.cp-benefits{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem}.cp-benefit{padding:1.4rem;background:#fff;border-radius:10px;text-align:center;box-shadow:0 7px 22px rgba(15,40,75,.08);font-weight:800}.cp-icon{width:40px;height:40px;margin:0 auto .8rem;display:grid;place-items:center;border-radius:10px;background:#063b82;color:#fff}.cp-faq{border:1px solid #dce4ee;border-radius:9px;overflow:hidden;background:#fff}.cp-faq details{padding:1rem;border-bottom:1px solid #e6ecf3}.cp-faq details:last-child{border:0}.cp-faq summary{cursor:pointer;color:#063b82;font-weight:800}.cp-faq p{color:#64748b;margin:.7rem 0 0}
    @media(max-width:760px){.cp-page{padding-top:9.5rem}.cp-nav{margin-top:.5rem}.cp-nav-in{justify-content:flex-start;padding-inline:.6rem}.cp-plans,.cp-benefits,.cp-summary{grid-template-columns:1fr}.cp-hero{padding-inline:0}.cp-benefits{grid-template-columns:1fr 1fr}}
  `}</style>
  <nav className="cp-nav" aria-label="Online course sections"><div className="cp-wrap cp-nav-in"><Link to="/online-drivers-ed">Home</Link><Link to="/online-drivers-ed/details">Course Details</Link><Link className="active" aria-current="page" to="/online-drivers-ed/pricing">Pricing</Link><Link to="/online-drivers-ed/permit">Permit</Link><Link to="/online-drivers-ed/driver-license">Driver License</Link><Link to="/">Behind the Wheel</Link></div></nav>
  <section className="cp-hero"><div className="cp-wrap"><h1 className="cp-title">Get Your California Driver's Permit!</h1><div className="cp-plans">{plans.map(plan=><article className="cp-plan" key={plan.name}><h2>{plan.name}</h2><div className="cp-price">{plan.price}</div><ul>{plan.features.map(f=><li key={f}>{f}</li>)}</ul><Link to="/register" className="cp-btn">{plan.action}</Link></article>)}</div></div></section>
  <section className="cp-section"><div className="cp-wrap"><div className="cp-summary"><img src="/register-img.png" alt="Online course study materials" width="735" height="490" loading="lazy" decoding="async"/><div><h2 style={{fontFamily:'var(--font-display)',fontSize:'2rem'}}>Course Summary</h2><p style={{color:'#64748b',lineHeight:1.8}}>Get your instruction permit with our California DMV-approved online course. Learn everything needed to become a safe, confident driver—including road rules, signs, accident prevention and the effects of drugs and alcohol.</p></div></div></div></section>
  <section className="cp-section"><div className="cp-wrap"><h2 className="cp-heading">Why Choose Us</h2><div className="cp-benefits">{benefits.map((b,i)=><div className="cp-benefit" key={b}><div className="cp-icon">{i+1}</div>{b}</div>)}</div></div></section>
  <section className="cp-section"><div className="cp-wrap"><h2 style={{fontFamily:'var(--font-display)',fontSize:'2rem'}}>Frequently Asked Questions</h2><div className="cp-faq">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
  </div>
}
